version: '2'

services:
 php:
   build: .
   ports:
     - "3000:80"
   restart: always
   volumes:
     - .:/var/www/html
 db:
   image: mysql:5.7
   ports:
     - "3307:3306"
   environment:
     MYSQL_ROOT_PASSWORD: 123456
     MYSQL_USER: username
     MYSQL_PASSWORD: password
     MYSQL_DATABASE: silverstripe
 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   environment:
     MYSQL_USER: user
     MYSQL_PASSWORD: password
     MYSQL_ROOT_PASSWORD: 123456
     MYSQL_ROOT_PASSWORD: root
   ports:
     - "3002:80"
   links:
     - db

